name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v4.0.1
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yaml
          python-version: 3.12.13
          auto-activate: false
          channels: conda-forge

      - name: Check format, lint, and type
        run: |
          ruff format --check
          ruff check
          pyright
